### ISSUE TITLE
[Inquiry] gitbridge.datadir

### ISSUE THREAD

**Issue by abdulkarim-itani** [cqse/harvest-git-bridge#1]
Hello,

Thank you for your amazing project. I am currently migrating our projecta out of harvest and i am facing an issue with:

Gitbridge.datadir

What should this attribute be used for

**Comment by agoeb** [comment]
Hi @DesertCore ,

thanks for getting in touch. The `gitbringe.datadir` should point to a directory that is used by the git bridge for metadata. In particular, it holds:

- the result files from calling Harvest, i.e. the `hsv.log`
- some files for keeping track of the mirroring progress, i.e. which changes have already been written to the git repository
- optionally, a user-provided file `authors.properties` in order to map Harvest users to git committers (as outlined in the README)

I'll try and update the docs as well as add some comments to the `build.gradle` file. Of course, you are more than welcome to issue a pull request in case you'd like to do so yourself.

**Comment by abdulkarim-itani** [comment]
Thank you @agoeb for your fast prompt. It is clear now.
So the `gitbridge.datadir` shall contain the execution data, while the process is running. 
Also contains `authors.properties`

I am facing an issue with update git command:

> PS C:\harvest-git-bridge-master\harvest-git-bridge-master> .\update-git.bat
> "C:\harvest-git-bridge-master\harvest-git-bridge-master\update-git.bat"
> ECHO is off.
> 
> > Task :updateGit FAILED
> executing [hsv, -b, __TODO__, -en, __TODO__, -o, C:\harvest-git-bridge-master\Git2/hsv.log, -st, __TODO__, -prompt, -vp, __TODO__, -s, *, -iv, av, -id, sd, 01/01/1970, 07/12/2019] in C:\harvest-git-bridge-master\Git2
> 
> 
> FAILURE: Build failed with an exception.
> 
> * Where:
> Script 'C:\harvest-git-bridge-master\harvest-git-bridge-master\gradle\base.gradle' line: 23        
> 
> * What went wrong:
> Execution failed for task ':updateGit'.
> > java.io.IOException: Cannot run program "hsv" (in directory "C:\harvest-git-bridge-master\Git2"): CreateProcess error=2, The system cannot find the file specified
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 1s
> 1 actionable task: 1 executed

I am running the bridge from the git server and I started to guess that we need to run this bridge on the same client that holds the Harvest application, is that true ?

Because the exception is mentioning an hsv command, cannot be found.

Finally, It would my pleasure to contribute to this project. I will write a very detailed usage description to the project's docs .

**Comment by agoeb** [comment]
Yeah, you need the Harvest Command-Line Tools (specifically the `hsv` and `hco` executables) as well as a `git` client available in the `PATH` of the machine you execute the git bridge on.
